# Generated by Django 2.0.2 on 2018-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(default='', max_length=255)),
                ('domain_name', models.CharField(default='', max_length=200)),
                ('introduction', models.CharField(default='', max_length=255)),
                ('wechat', models.CharField(default='', max_length=200)),
                ('weibo', models.CharField(default='', max_length=200)),
                ('qq', models.CharField(default='', max_length=200)),
                ('nick', models.CharField(default='', max_length=200)),
                ('cookie', models.CharField(blank=True, default='', max_length=32, null=True)),
            ],
        ),
    ]
