# Generated by Django 2.0.2 on 2018-10-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_articletag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='pid',
        ),
        migrations.AddField(
            model_name='article',
            name='tagid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
